version: '3.8'
services:
  app:
    build: ./
    env_file:
      - .env
    ports:
      - "8000:8000"

    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --address :10123 --console-address ":10124" /data/minio
    env_file:
      - .env

    ports:
      - "${MINIO_SERVER_PORT}:${MINIO_SERVER_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:10123/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./_data/minio:/data